sudo: required
services:
  - docker

before_install:
  - docker build -t rgadeus/docker-multitest -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true rgadeus/docker-multitest npm run test -- --coverage

after_success:
  - docker build -t rgadeus/multi-client ./client
  - docker build -t rgadeus/multi-nginx ./nginx
  - docker build -t rgadeus/multi-server ./server
  - docker build -t rgadeus/multi-worker ./worker
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERID" --password-stdin
  - docker push rgadeus/multi-client
  - docker push rgadeus/multi-nginx
  - docker push rgadeus/multi-server
  - docker push rgadeus/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multicontainer"
  env: "DockerMulticontainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-368157862279"
  bucket_path: "docker-multicontainer"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"